on:
  push:
  pull_request:
name: test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod

      - name: Exec Test
        run: |
          cd ./services/goApi
          go test ./... -coverprofile=coverage.out

      - uses: k1LoW/octocov-action@v0